### ISSUE TITLE
[Design request] 와이어프레임 

### ISSUE THREAD

**Issue by feldblume5263** [hasen-sprung/iOS_project-Emotion#2]
## New features needed
와이어프레임 대략적 작성

**Comment by feldblume5263** [comment]
<img width="1248" alt="Screen Shot 2021-09-12 at 12 23 49 PM" src="https://user-images.githubusercontent.com/53016167/132970926-67a27254-6568-4c54-a9b4-478e1ece7e0b.png">
<img width="1263" alt="Screen Shot 2021-09-12 at 12 24 02 PM" src="https://user-images.githubusercontent.com/53016167/132970932-fbb1bfea-28cf-4ce0-b84e-72464c480fda.png">
<img width="1356" alt="Screen Shot 2021-09-12 at 12 24 14 PM" src="https://user-images.githubusercontent.com/53016167/132970935-dac400d6-3c03-4268-bae9-6305d6ce0e77.png">
<img width="1257" alt="Screen Shot 2021-09-12 at 12 24 26 PM" src="https://user-images.githubusercontent.com/53016167/132970940-d7a47aae-5f09-48ab-8073-af8928f3861b.png">

**Comment by dikonghh** [comment]
디자인 컨셉 레퍼런스 첨부합니다!
<img width="418" alt="스크린샷 2021-09-06 오후 5 32 37" src="https://user-images.githubusercontent.com/89839291/132974005-19e54302-3993-45ce-b7c1-a2da4fc957c4.png">
![다운로드](https://user-images.githubusercontent.com/89839291/132974007-6af11b17-b40f-48d3-af08-ce571e2c0854.jpeg)
<img width="1345" alt="스크린샷 2021-09-06 오후 5 46 08" src="https://user-images.githubusercontent.com/89839291/132974008-269738e0-656e-491b-bbde-409fa4186d03.png">
![Active Social Branding](https://user-images.githubusercontent.com/89839291/132974013-4c68c9cc-8feb-429c-afc6-ed19f853bc52.png)
![IMG_8764](https://user-images.githubusercontent.com/89839291/132974015-b15903f8-f9b5-4e6f-8b4a-9a59df16a821.PNG)
![Join the Conversation](https://user-images.githubusercontent.com/89839291/132974017-4789cf85-ead6-4fa2-af7f-e83592ef88ea.png)
<img width="1363" alt="스크린샷 2021-09-06 오후 5 53 43" src="https://user-images.githubusercontent.com/89839291/132974018-276684da-5f5c-4721-9b0f-01695e5f7709.png">
![Beautiful weather app UI concepts we wish existed](https://user-images.githubusercontent.com/89839291/132974022-a21c662a-221b-4118-90ea-949128b973fe.png)
![Payment Dots __ Mobile App](https://user-images.githubusercontent.com/89839291/132974024-97cb8bde-bd34-4481-b4d8-67c51887ed0c.png)
<img width="591" alt="스크린샷 2021-09-12 오후 2 09 22" src="https://user-images.githubusercontent.com/89839291/132974032-ce13691c-ee3e-47b1-9c60-5a6334245015.png">
<img width="940" alt="스크린샷 2021-09-12 오후 2 14 30" src="https://user-images.githubusercontent.com/89839291/132974035-7a602005-3ccb-4cb4-8598-2d90f7aab0bb.png">
<img width="558" alt="스크린샷 2021-09-12 오후 2 10 37" src="https://user-images.githubusercontent.com/89839291/132974040-94b7a210-d791-4238-b812-34057bfefe97.png">

**Comment by feldblume5263** [comment]
![IMG_6A39E05B4588-1](https://user-images.githubusercontent.com/53016167/132974437-bceac84c-94fe-4c15-9f15-1a1c6bc6bb43.jpeg)
