### ISSUE TITLE
[Design request] 게이지 페이지 디자인

### ISSUE THREAD

**Issue by dikonghh** [hasen-sprung/iOS_project-Emotion#3]
[앱디자인_게이지.zip](https://github.com/hasen-sprung/iOS_project-Emotion/files/7184825/_.zip)

게이지 페이지 초안 디자인입니다.
1. 우선 행성 아이콘을 만들어보았는데 귀엽지가 않아서 수정할 예정이라 우선 이걸로 만들어보고 나중에 바꾸는게 좋을 것 같아요!
기분에 어울리는 행성 아이콘 (4-5개)를 디자인할 예정입니다.
2. 게이지의 그라데이션 컬러와 배경, 포인트 컬러(키컬러)를 정했습니다.
(아이콘 때문인지 우주의 몽환적 느낌보다 지구멸망같은 느낌이 나서 아이콘 수정 후 바뀔 수도 있어요)
3. 게이지 선택 후 입력창을 아이콘 색깔로 하기로 했었는데, 팝업창이 그 색이 되면 너무 안예뻐서 고민..
해보다가 작은 팝업창은 어떨까 하고 추가로 만들어봤어요.
+행성 자체가 원래 다 동그랗고 그 원 안에 다른 색의 모양으로 구분하는데, 이건 색이 변해야되니까 다른 색이랑 혼합이 불가능해서 디자인하기 힘들 수도 있을 것 같다는 생각! 하다가 안되면 별이나 더 단순한 그래픽으로 바꿀게요!

**Comment by dikonghh** [comment]
이거 추가합니다!
[컬러1](https://user-images.githubusercontent.com/89839291/133769587-0c33f1f9-2bd1-4cde-9d4f-8e02bfb273a2.png)
당

**Comment by dikonghh** [comment]
이거 추가!
![컬러1](https://user-images.githubusercontent.com/89839291/133769692-3b13f5f4-cb4c-4168-aa2f-ca427917e485.png)

**Comment by ejei0g** [comment]
https://user-images.githubusercontent.com/20364535/134279273-773bf313-b8ea-4a39-afa0-0195111a52c7.mp4

**Comment by dikonghh** [comment]
![게이지1 – 3](https://user-images.githubusercontent.com/89839291/134464386-67ac12ec-43fd-408b-a625-3fd09c73125a.png)
![게이지1 – 4](https://user-images.githubusercontent.com/89839291/134464389-3249e975-9030-4f19-98bb-c14c2609c8fe.png)
![도형](https://user-images.githubusercontent.com/89839291/134464391-a62d4be3-c26d-4182-9a37-e72cfe2b4326.png)
![컬러 1vs2](https://user-images.githubusercontent.com/89839291/134464396-239c2827-a170-40ff-b5ff-5f18d2a58f0a.png)

[도형NEW.zip](https://github.com/hasen-sprung/iOS_project-Emotion/files/7215494/NEW.zip)

행성 (도형) 디자인 수정 버전입니다.
감정대로 변하는 의미를 담아서 더 단순한 모양으로 만들었고,
컬러 그라데이션에 그린을 넣어서 다른 버전을 만들어봤는데 둘 중 어떤 컬러가 더 좋은지 궁금해요!

**Comment by dikonghh** [comment]
[도형SVG.zip](https://github.com/hasen-sprung/iOS_project-Emotion/files/7236554/SVG.zip)

**Comment by dikonghh** [comment]
최종 컬러
![pick](https://user-images.githubusercontent.com/89839291/135009275-77597e04-4e53-4bd5-8602-41455fb70ff0.png)

후보
![1](https://user-images.githubusercontent.com/89839291/135009320-18a245b6-9cb5-4c78-b27f-c1ff494c7940.png)
![2](https://user-images.githubusercontent.com/89839291/135009325-5c1e1014-e7c3-46d6-a556-2aa8806a9427.png)
![4](https://user-images.githubusercontent.com/89839291/135009329-62d5873f-ad4d-4ecd-a1b6-1c0cb77b4b05.png)

**Comment by feldblume5263** [comment]
SVG 파일 확인했습니다. c파일과 p파일 확인 결과, 두 파일 모두 동일해서 일단은 c 파일로 계속 주시면 될 것 같습니다!
감사합니다!

**Comment by ejei0g** [comment]
탭바 관련해서 참고하시면 좋을거 같아요 https://iosexample.com/tag/tab-bars/

**Comment by feldblume5263** [comment]
현재까지 게이지뷰 진행상황입니다.
   
![게이지뷰_진행상황](https://user-images.githubusercontent.com/53016167/135077964-c4a3d0b3-51c0-4dce-b596-042e68dd75d8.gif)
