### ISSUE TITLE
[Feature request] 그라데이션 색 추가 ( 2->3)

### ISSUE THREAD

**Issue by feldblume5263** [hasen-sprung/iOS_project-Emotion#44]
## New features needed
기존의 두가지 색에서 3가지 색으로 추가

맨 위에 #FCFFB9 추가해서
#FCFFB9 ~ #FFB5AF ~ #A29FFF

게이지와 메인 배경 색은
#FFFEF0

**Comment by ejei0g** [comment]
단순히 하나의 액션으로 처리하기가 힘들기 때문에, 고민중... 액션을 두개로 나누고 (탑->중간), (중간,마지막) 두개의 액션을 시퀸스액션으로 묶어보면?

**Comment by ejei0g** [comment]
기존의 현재 색상을 추적하는 방법에서 figure의 수치를 기준으로 0.5에서 top->mid, mid->bot으로변경되게 수정.
추가로 toColor함수를 사용하는 경우 각각의 비율이 바뀌므로 (0~0.5 = 100%, 0.5~1.0 = 100%) 앞에는 *2 뒤에는 /2를 해주었다
